[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
eframe = "0.28.0"
egui = "0.28.0"
serde = "1.0.210"

protocol = { path = "../protocol" }
core = { path = "../core" }
