[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
ecolor = "0.29.1"
emath = "0.29.1"
serde = { version = "1.0.210", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }

core = { path = "../core" }
