[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
ecolor = { version = "0.28", features = ["serde"] }
emath = { version = "0.28", features = ["serde"] }

macros = { path = "../macros" }
rand = "0.8.5"
